// <auto-generated />
using System;
using AM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Test.Infrastructure.Migrations
{
    [DbContext(typeof(AMContext))]
    [Migration("20241212233246_rouri1")]
    partial class rouri1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.ApplicationCore.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Prestataire", b =>
                {
                    b.Property<int>("PrestataireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestataireId"));

                    b.Property<int>("Appreciation")
                        .HasColumnType("int");

                    b.Property<string>("PrestataireNom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrestatairePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrestataireTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialiteFK")
                        .HasColumnType("int");

                    b.Property<double>("TarifHoraire")
                        .HasColumnType("float");

                    b.HasKey("PrestataireId");

                    b.HasIndex("SpecialiteFK");

                    b.ToTable("Prestataires");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Prestation", b =>
                {
                    b.Property<int>("ClientFK")
                        .HasColumnType("int");

                    b.Property<int>("PrestataireFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("HeureRDV");

                    b.Property<int>("NbrHeures")
                        .HasColumnType("int");

                    b.HasKey("ClientFK", "PrestataireFK", "HeureDebut");

                    b.HasIndex("PrestataireFK");

                    b.ToTable("Prestations");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Specialite", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("intitule")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Specialites");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Prestataire", b =>
                {
                    b.HasOne("Test.ApplicationCore.Domain.Specialite", "MySpecialite")
                        .WithMany("Prestataires")
                        .HasForeignKey("SpecialiteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MySpecialite");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Prestation", b =>
                {
                    b.HasOne("Test.ApplicationCore.Domain.Client", "Myclient")
                        .WithMany("Prestations")
                        .HasForeignKey("ClientFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.ApplicationCore.Domain.Prestataire", "MyPrestataire")
                        .WithMany("Prestations")
                        .HasForeignKey("PrestataireFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyPrestataire");

                    b.Navigation("Myclient");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Client", b =>
                {
                    b.Navigation("Prestations");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Prestataire", b =>
                {
                    b.Navigation("Prestations");
                });

            modelBuilder.Entity("Test.ApplicationCore.Domain.Specialite", b =>
                {
                    b.Navigation("Prestataires");
                });
#pragma warning restore 612, 618
        }
    }
}
